#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main() {
    // Define the HTML content
    const char *html_content =
        "<!DOCTYPE html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        "    <meta charset=\"UTF-8\">\n"
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "    <title>Simple CGI Page</title>\n"
        "</head>\n"
        "<body>\n"
        "    <h1>Welcome to My CGI Page</h1>\n"
        "    <p>This is a simple HTML page generated by a C CGI script.</p>\n"
        "</body>\n"
        "</html>\n";

    // Calculate content length
    int content_length = strlen(html_content);

    // Send the HTTP headers
    printf("Content-Type: text/html\r\n");
    printf("Content-Length: %d\r\n", content_length);
    printf("\r\n");

    // Send the HTML content
    printf("%s", html_content);

    return 0;
}